<script lang="ts">
	import { invoke } from '@tauri-apps/api/core';
	import { listen } from '@tauri-apps/api/event';
	import type { UnlistenFn } from '@tauri-apps/api/event';
	import { LyricPlayer, FluidBackground } from '../components/lyrics';
	import { extractTheme } from '../components/lyrics/color';
	import { parseLyrics } from '../lib/lyric-parser';
	import type { LyricLine, LyricTheme } from '../lib/types/lyrics';
	import { LiquidGlass } from '../lib/liquid-glass';

	// ---------------------------------------------------------------------------
	// Audio-backend types (mirror audio_core::tauri_api serde shapes; Tauri
	// emits/serializes these as JSON. The frontend's CSS layer only needs the
	// shapes used here — full bindings are generated by Tauri in
	// `src-tauri/gen/schemas/` on `pnpm tauri dev` / `pnpm tauri build`.)
	// ---------------------------------------------------------------------------

	type PlaybackState =
		| 'idle'
		| 'playing'
		| 'paused'
		| 'buffering'
		| 'crossfading'
		| 'stopped';

	/** Mirrors `audio_core::tauri_api::SongInfo`. Optional fields use `?`. */
	interface SongInfo {
		path: string;
		title?: string;
		artist?: string;
		album?: string;
		duration_secs?: number;
	}

	/** Mirrors `audio_core::tauri_api::PlaybackProgressInfo`. */
	interface PlaybackProgressInfo {
		position_secs: number;
		duration_secs?: number;
		buffer_level: number;
	}

	/**
	 * Mirrors `audio_core::tauri_api::AudioEventInfo` (a `#[serde(tag = "kind",
	 * rename_all = "snake_case")]` tagged enum).
	 */
	type AudioEventInfo =
		| { kind: 'state_changed'; state: PlaybackState }
		| { kind: 'progress'; progress: PlaybackProgressInfo }
		| { kind: 'track_ended'; path: string }
		| { kind: 'crossfade_started'; from_path: string; to_path: string }
		| { kind: 'error'; message: string }
		| { kind: 'next_track_ready'; path: string };

	// ---------------------------------------------------------------------------
	// Reactive state (Svelte 5 runes)
	// ---------------------------------------------------------------------------

	/** Current playback position, in seconds. */
	let currentTime = $state(0);
	/** Track duration, in seconds (null when unknown). */
	let duration = $state<number | null>(null);
	/** Whether the engine is actively playing / crossfading. */
	let playing = $state(false);
	/** True while the user is dragging the seek bar (suppresses event updates). */
	let isSeeking = $state(false);
	/** Track currently loaded in the engine (null when nothing is loaded). */
	let currentTrack = $state<SongInfo | null>(null);
	/** Lyric lines fed to `LyricPlayer`. Empty until a lyric file is loaded. */
	let lyricLines = $state<LyricLine[]>([]);
	/** Album-art URL — drives theme extraction + FluidBackground. */
	let albumArtUrl = $state('');
	/** Theme derived from the album art (palette + accent + light flag). */
	let theme = $state<LyricTheme | undefined>(undefined);

	// ---------------------------------------------------------------------------
	// Engine wiring: event stream + 2-second fallback poll
	// ---------------------------------------------------------------------------

	$effect(() => {
		let unlistenPromise: Promise<UnlistenFn> | null = null;
		let pollId: ReturnType<typeof setInterval> | null = null;
		let mounted = true;

		// Ask the shell to spin up the engine event-forwarding task. The task
		// polls the engine every 100 ms and emits `audio-event`s.
		// `start_event_stream` is idempotent in shape — calling it again spawns
		// a second polling task, so this effect should run once per mount.
		invoke('start_event_stream').catch((e) =>
			console.error('[NowPlaying] start_event_stream failed:', e),
		);

		// Listen for forwarded engine events. Always tear down via unlisten.
		unlistenPromise = listen<AudioEventInfo>('audio-event', (ev) => {
			if (!mounted) return;
			const event = ev.payload;
			switch (event.kind) {
				case 'state_changed':
					playing = event.state === 'playing' || event.state === 'crossfading';
					break;
				case 'progress':
					if (!isSeeking) currentTime = event.progress.position_secs;
					if (event.progress.duration_secs) {
						duration = event.progress.duration_secs;
					}
					break;
				case 'track_ended':
					playing = false;
					// The engine will follow up with a `state_changed` and, if
					// gapless / crossfading, a new track's progress events.
					break;
				case 'crossfade_started':
					// Mid-crossfade; new track's progress events follow.
					break;
				case 'next_track_ready':
					// Future prompt wires currentTrack + lyric auto-load here.
					break;
				case 'error':
					console.warn('[NowPlaying] engine error:', event.message);
					break;
			}
		});

		// Fallback poll: if events are missed (e.g. during hot-reload, or if
		// the engine hasn't yet emitted any), refresh state every 2 seconds.
		pollId = setInterval(async () => {
			if (!mounted) return;
			try {
				const state = await invoke<PlaybackState>('get_state');
				if (!mounted) return;
				playing = state === 'playing' || state === 'crossfading';
				const progress = await invoke<PlaybackProgressInfo | null>('get_progress');
				if (!mounted) return;
				if (progress) {
					if (!isSeeking) currentTime = progress.position_secs;
					if (progress.duration_secs) duration = progress.duration_secs;
				}
			} catch (e) {
				console.warn('[NowPlaying] fallback poll failed:', e);
			}
		}, 2000);

		// Also fetch the initial state once so the transport UI is correct on
		// the very first paint (before the first event or poll fires).
		invoke<PlaybackState>('get_state')
			.then((s) => {
				if (mounted) {
					playing = s === 'playing' || s === 'crossfading';
				}
			})
			.catch((e) => console.warn('[NowPlaying] initial get_state:', e));

		return () => {
			mounted = false;
			if (pollId != null) clearInterval(pollId);
			// `listen` resolves asynchronously; if the effect tears down before
			// the registration completes we still need to call unlisten once
			// it does, so chain it on the resolved promise.
			if (unlistenPromise) unlistenPromise.then((un) => un());
		};
	});

	// ---------------------------------------------------------------------------
	// Theme extraction from album art
	// ---------------------------------------------------------------------------

	$effect(() => {
		const url = albumArtUrl;
		if (!url) {
			theme = undefined;
			return;
		}
		let cancelled = false;
		extractTheme(url)
			.then((t) => {
				if (!cancelled) theme = t ?? undefined;
			})
			.catch((e) => console.warn('[NowPlaying] extractTheme failed:', e));
		return () => {
			cancelled = true;
		};
	});

	// The lyric player's `theme.light` flag drives whether it renders dark
	// text on a light backdrop. Tie it to the global app theme so the lyrics
	// stay legible in light mode — when album art is present we keep the
	// extracted colour/palette but force the `light` flag to follow the app
	// shell; when no art is loaded we still pass a minimal theme so the
	// `.light` class flips the foreground to dark.
	const lyricTheme = $derived<LyricTheme | undefined>(
		theme
			? { ...theme, light: true }
			: { color: '#111111', palette: [], light: true },
	);

	// ---------------------------------------------------------------------------
	// Transport controls
	// ---------------------------------------------------------------------------

	async function togglePlay(): Promise<void> {
		if (playing) {
			try {
				await invoke('pause');
			} catch (e) {
				console.error('[NowPlaying] pause failed:', e);
			}
		} else {
			try {
				await invoke('resume');
			} catch (e) {
				console.error('[NowPlaying] resume failed:', e);
			}
		}
	}

	function onSeekInput(e: Event): void {
		const target = e.target as HTMLInputElement;
		isSeeking = true;
		currentTime = Number(target.value);
	}

	async function onSeekCommit(e: Event): Promise<void> {
		const target = e.target as HTMLInputElement;
		const position = Number(target.value);
		isSeeking = false;
		try {
			await invoke('seek', { positionSecs: position });
		} catch (e) {
			console.error('[NowPlaying] seek failed:', e);
		}
	}

	// ---------------------------------------------------------------------------
	// Derived display values
	// ---------------------------------------------------------------------------

	const titleText = $derived(currentTrack?.title ?? 'Nothing playing');
	const artistText = $derived(currentTrack?.artist ?? '—');
	const currentTimeMs = $derived(Math.round(currentTime * 1000));
	const seekMax = $derived(Math.max(0, duration ?? 0));
	const timeLabel = $derived(`${formatTime(currentTime)} / ${formatTime(duration ?? 0)}`);

	function formatTime(secs: number): string {
		if (!Number.isFinite(secs) || secs < 0) secs = 0;
		const m = Math.floor(secs / 60);
		const s = Math.floor(secs % 60);
		return `${m}:${s.toString().padStart(2, '0')}`;
	}

	// ---------------------------------------------------------------------------
	// Lyric loading (manual, for the MVP)
	// ---------------------------------------------------------------------------
	//
	// When a lyric file path is available (next to the loaded track or embedded
	// in its tags), parse it and feed the lines to `LyricPlayer`. The full
	// integration — reading the lyric file from disk via a Tauri command and
	// auto-deriving the format via `parseLyrics` — is a follow-up prompt.
	//
	// Example (commented out, awaiting the lyric-file-read command):
	//
	// import { readTextFile } from '@tauri-apps/plugin-fs';
	// async function loadLyricsFromFile(path: string): Promise<void> {
	//   const content = await readTextFile(path);
	//   const lines = await parseLyrics(content); // auto-detects format
	//   lyricLines = lines;
	// }
	//
	// For test-driving the renderer without a track:
	// parseLyrics('[00:01.00]Hello world\n[00:03.00]This is a demo')
	//   .then((lines) => (lyricLines = lines));
</script>

<section class="now-playing">
	<FluidBackground {theme} playing={playing} mode="fluid" />

	<div class="lyric-layer">
		<LyricPlayer
			lyrics={lyricLines}
			currentTime={currentTimeMs}
			{playing}
			onLineChange={(_i: number) => {
				/* future: sync SCM highlight / external interpreters */
			}}
			theme={lyricTheme}
			enableFluidBackground={false}
			enableBlur={true}
			enableScale={true}
			alignPosition={0.35}
		/>
	</div>

	<LiquidGlass roundness={0} accent="#bef264" contrast="light">
		<div class="transport">
			<div class="track-info">
				<div class="title">{titleText}</div>
				<div class="artist">{artistText}</div>
			</div>

			<div class="seek-row">
				<span class="time">{timeLabel}</span>
				<input
					type="range"
					min="0"
					max={seekMax}
					step="0.1"
					value={Math.min(currentTime, seekMax)}
					oninput={onSeekInput}
					onchange={onSeekCommit}
					aria-label="Seek"
				/>
			</div>

			<div class="button-row">
				<button type="button" class="play" onclick={togglePlay} aria-label={playing ? 'Pause' : 'Play'}>
					{#if playing}❚❚{:else}▶{/if}
				</button>
			</div>
		</div>
	</LiquidGlass>
</section>

<style>
	.now-playing {
		position: relative;
		height: 100%;
		width: 100%;
		overflow: hidden;
		background:
			radial-gradient(circle at 20% -10%, var(--uto-ambient-tint), transparent 55%),
			var(--uto-bg);
	}

	.lyric-layer {
		position: absolute;
		inset: 0;
		/* The transport overlay sits at the bottom; the lyric area mimics the
		   Apple Music layout where the active line floats ~35% from the top. */
		padding: 48px 28px 180px;
		z-index: 1;
	}

	.transport {
		position: absolute;
		left: 0;
		right: 0;
		bottom: 0;
		z-index: 2;
		padding: 16px 24px 18px;
		display: flex;
		flex-direction: column;
		gap: 10px;
	}

	.track-info {
		display: flex;
		flex-direction: column;
		gap: 2px;
	}
	.title {
		font-size: 16px;
		font-weight: 600;
		color: var(--uto-text-strong);
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
	.artist {
		font-size: 13px;
		color: var(--uto-text);
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.seek-row {
		display: flex;
		align-items: center;
		gap: 12px;
	}
	.seek-row .time {
		font-variant-numeric: tabular-nums;
		font-size: 12px;
		color: var(--uto-text);
		min-width: 96px;
	}
	.seek-row input[type='range'] {
		flex: 1;
		accent-color: var(--uto-accent-green, #bef264);
		height: 4px;
	}

	.button-row {
		display: flex;
		align-items: center;
		justify-content: center;
		gap: 12px;
		margin-top: 4px;
	}
	.button-row .play {
		width: 56px;
		height: 56px;
		border-radius: 50%;
		border: none;
		background: var(--uto-accent-green, #bef264);
		color: var(--uto-play-text);
		font-size: 20px;
		cursor: pointer;
		transition: transform 0.12s ease, filter 0.12s ease;
		box-shadow: 0 8px 24px rgba(190, 242, 100, 0.25);
	}
	.button-row .play:hover {
		transform: scale(1.05);
		filter: brightness(1.06);
	}
	.button-row .play:active {
		transform: scale(0.96);
	}
</style>
