// This file is part of utoaudio, licensed under AGPL-3.0.
//
// `audio-ffi` - Tauri command bindings bridging the frontend to `audio-core`.

use std::sync::Arc;
use std::time::Duration;

use tokio::sync::Notify;

pub mod library;
pub mod settings;

// Re-export the library DB handle so the Tauri shell can `use audio_ffi::LibraryDb`.
pub use library::LibraryDb;

// Re-export every serde-serializable type from `audio_core::tauri_api` so the
// frontend TypeScript bindings (generated by Tauri from the command
// signatures below) can reference them through this crate's namespace.
pub use audio_core::tauri_api::{
    AudioEngine, AudioEventInfo, ConvolverConfig, CrossfadeConfig,
    CrossfadeCurveSerde, EqualizerPreset, EQBand, FxConfig,
    PlaybackProgressInfo, PlaybackState, SongInfo, Uac2DeviceInfo,
};

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FileEntry {
    pub name: String,
    pub path: String,
    pub is_directory: bool,
    pub size: Option<u64>,
    pub modified: Option<i64>,
}

pub mod commands {
    use super::{
        Arc, AudioEngine, AudioEventInfo, ConvolverConfig, CrossfadeConfig,
        Duration, FileEntry, EqualizerPreset, FxConfig, Notify,
        PlaybackProgressInfo, PlaybackState, SongInfo, Uac2DeviceInfo,
    };
    use std::collections::HashSet;
    use std::fs;
    use std::path::{Path, PathBuf};
    use std::time::UNIX_EPOCH;
    use tauri::Emitter;

    // -------------------------------------------------------------------
    // Lifecycle / capability commands
    // -------------------------------------------------------------------
    #[tauri::command]
    pub fn init(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<(), String> {
        engine.init();
        Ok(())
    }

    #[tauri::command]
    pub fn prepare(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        preferred_sample_rate: Option<u32>,
    ) -> Result<(), String> {
        engine
            .prepare(preferred_sample_rate)
            .map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn is_initialized(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<bool, String> {
        Ok(engine.is_initialized())
    }

    // -------------------------------------------------------------------
    // Playback commands
    // -------------------------------------------------------------------
    #[tauri::command]
    pub fn play(engine: tauri::State<'_, Arc<AudioEngine>>, song: SongInfo) -> Result<(), String> {
        engine.play(song).map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn queue_next(engine: tauri::State<'_, Arc<AudioEngine>>, song: SongInfo) -> Result<(), String> {
        engine.queue_next(song).map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn pause(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<(), String> {
        engine.pause().map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn resume(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<(), String> {
        engine.resume().map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn stop(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<(), String> {
        engine.stop().map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn seek(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        position_secs: f64,
    ) -> Result<(), String> {
        engine.seek(position_secs).map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn set_volume(engine: tauri::State<'_, Arc<AudioEngine>>, volume: f32) -> Result<(), String> {
        engine.set_volume(volume).map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn get_state(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<PlaybackState, String> {
        Ok(engine.get_state())
    }

    #[tauri::command]
    pub fn get_progress(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<Option<PlaybackProgressInfo>, String> {
        Ok(engine.get_progress())
    }

    #[tauri::command]
    pub fn poll_event(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<Option<AudioEventInfo>, String> {
        Ok(engine.poll_event())
    }

    #[tauri::command]
    pub fn current_path(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<Option<String>, String> {
        Ok(engine.current_path())
    }

    #[tauri::command]
    pub fn skip_to_next(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<(), String> {
        engine.skip_to_next().map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn set_playback_speed(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        speed: f32,
    ) -> Result<(), String> {
        engine.set_playback_speed(speed).map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn playback_speed(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<Option<f32>, String> {
        Ok(engine.playback_speed())
    }

    #[tauri::command]
    pub fn sample_rate(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<Option<u32>, String> {
        Ok(engine.sample_rate())
    }

    #[tauri::command]
    pub fn channels(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<Option<usize>, String> {
        Ok(engine.channels())
    }

    // -------------------------------------------------------------------
    // DSP / FX commands
    // -------------------------------------------------------------------
    #[tauri::command]
    pub fn set_equalizer(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        preset: EqualizerPreset,
    ) -> Result<(), String> {
        engine.set_equalizer(&preset).map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn set_fx(engine: tauri::State<'_, Arc<AudioEngine>>, config: FxConfig) -> Result<(), String> {
        engine.set_fx(config).map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn set_convolver(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        config: ConvolverConfig,
    ) -> Result<(), String> {
        engine.set_convolver(config).map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn set_convolver_ir(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        coeffs: Vec<Vec<f32>>,
    ) -> Result<(), String> {
        engine.set_convolver_ir(coeffs).map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn clear_convolver_ir(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<(), String> {
        engine.clear_convolver_ir().map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn set_crossfade(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        config: CrossfadeConfig,
    ) -> Result<(), String> {
        engine.set_crossfade(config).map_err(|e| e.to_string())
    }

    // -------------------------------------------------------------------
    // High-res / bit-perfect preferences
    // -------------------------------------------------------------------
    #[tauri::command]
    pub fn set_high_res_mode(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        enabled: bool,
    ) -> Result<(), String> {
        engine.set_high_res_mode(enabled);
        Ok(())
    }

    #[tauri::command]
    pub fn set_dap_bit_perfect_enabled(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        enabled: bool,
    ) -> Result<(), String> {
        engine.set_dap_bit_perfect_enabled(enabled);
        Ok(())
    }

    #[tauri::command]
    pub fn set_432hz_tuning_enabled(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        enabled: bool,
    ) -> Result<(), String> {
        engine.set_432hz_tuning_enabled(enabled);
        Ok(())
    }

    // -------------------------------------------------------------------
    // Hardware queries / shutdown
    // -------------------------------------------------------------------
    #[tauri::command]
    pub fn is_dac_available(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        preferred_sample_rate: Option<u32>,
    ) -> Result<bool, String> {
        engine
            .is_dac_available(preferred_sample_rate)
            .map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn shutdown(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<(), String> {
        engine.shutdown().map_err(|e| e.to_string())
    }

    #[cfg(feature = "uac2")]
    #[tauri::command]
    pub fn list_uac2_devices(
        engine: tauri::State<'_, Arc<AudioEngine>>,
    ) -> Result<Vec<Uac2DeviceInfo>, String> {
        Ok(engine.list_uac2_devices())
    }

    #[tauri::command]
    pub fn version() -> Result<String, String> {
        Ok("utoaudio audio-ffi 0.1.0".to_string())
    }

    // -------------------------------------------------------------------
    // Event forwarding
    // -------------------------------------------------------------------
    #[tauri::command]
    pub async fn start_event_stream(
        app_handle: tauri::AppHandle,
        engine: tauri::State<'_, Arc<AudioEngine>>,
        shutdown: tauri::State<'_, Arc<Notify>>,
    ) -> Result<(), String> {
        let engine = Arc::clone(&engine);
        let shutdown = Arc::clone(&shutdown);
        tauri::async_runtime::spawn(async move {
            let mut ticker = tokio::time::interval(Duration::from_millis(100));
            ticker.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
            ticker.reset();
            loop {
                tokio::select! {
                    _ = shutdown.notified() => break,
                    _ = ticker.tick() => {
                        let mut drained = 0;
                        while let Some(event) = engine.poll_event() {
                            let _ = app_handle.emit("audio-event", event);
                            drained += 1;
                            if drained >= 256 {
                                break;
                            }
                        }
                    }
                }
            }
        });
        Ok(())
    }

    // -------------------------------------------------------------------
    // Persistent settings
    // -------------------------------------------------------------------
    use crate::settings::load_settings as settings_load;
    use crate::settings::save_settings as settings_save;
    use crate::settings::Settings as AppSettings;

    #[tauri::command]
    pub fn get_settings() -> Result<serde_json::Value, String> {
        let s = settings_load()?;
        Ok(serde_json::to_value(&s).map_err(|e| e.to_string())?)
    }

    #[tauri::command]
    pub fn set_settings(settings: serde_json::Value) -> Result<(), String> {
        let mut current: AppSettings = settings_load().unwrap_or_default();
        if let Ok(partial) = serde_json::from_value::<AppSettings>(settings) {
            if !partial.enabled_extensions.is_empty() {
                current.enabled_extensions = partial.enabled_extensions;
            }
            if partial.equalizer.is_some() {
                current.equalizer = partial.equalizer;
            }
            if partial.crossfade.is_some() {
                current.crossfade = partial.crossfade;
            }
            if partial.convolver.is_some() {
                current.convolver = partial.convolver;
            }
            if partial.lyric_font_size.is_some() {
                current.lyric_font_size = partial.lyric_font_size;
            }
        }
        settings_save(&current)?;
        Ok(())
    }

    // -------------------------------------------------------------------
    // Filesystem scan commands (Library page)
    // -------------------------------------------------------------------
    const SCAN_MAX_DEPTH: u32 = 8;
    const SCAN_MAX_ENTRIES: usize = 50_000;

    #[tauri::command]
    pub fn scan_directory(path: String) -> Result<Vec<FileEntry>, String> {
        let root = PathBuf::from(&path);
        if !root.is_dir() {
            return Err(format!("not a directory: {}", path));
        }
        read_dir_entries(&root).map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn scan_library(
        roots: Vec<String>,
        extensions: Vec<String>,
    ) -> Result<Vec<FileEntry>, String> {
        let ext_set: HashSet<String> = extensions
            .into_iter()
            .map(|e| {
                let t = e.trim().to_lowercase();
                if t.starts_with('.') { t } else { format!(".{}", t) }
            })
            .collect();

        let mut entries = Vec::new();
        let mut visited = HashSet::new();

        for root_str in &roots {
            let root = PathBuf::from(root_str);
            let canon = root.canonicalize().unwrap_or_else(|_| root.clone());
            if !canon.is_dir() { continue; }
            walk_dir(&canon, 0, &ext_set, &mut visited, &mut entries);
            if entries.len() >= SCAN_MAX_ENTRIES { break; }
        }

        sort_entries(&mut entries);
        entries.truncate(SCAN_MAX_ENTRIES);
        Ok(entries)
    }

    fn read_dir_entries(dir: &Path) -> std::io::Result<Vec<FileEntry>> {
        let mut out = Vec::new();
        for entry in fs::read_dir(dir)? {
            let entry = match entry { Ok(e) => e, Err(_) => continue };
            let is_dir = entry.file_type().map(|ft| ft.is_dir()).unwrap_or(false);
            if let Some(fe) = build_file_entry(&entry.path(), is_dir) {
                out.push(fe);
            }
        }
        sort_entries(&mut out);
        Ok(out)
    }

    fn walk_dir(
        dir: &Path, depth: u32,
        ext_set: &HashSet<String>,
        visited: &mut HashSet<PathBuf>,
        out: &mut Vec<FileEntry>,
    ) {
        if depth >= SCAN_MAX_DEPTH { return; }
        let canon = dir.canonicalize().unwrap_or_else(|_| dir.to_path_buf());
        if !visited.insert(canon.clone()) { return; }

        let iter = match fs::read_dir(dir) {
            Ok(it) => it,
            Err(_) => { visited.remove(&canon); return; }
        };

        for entry in iter.flatten() {
            let path = entry.path();
            let is_dir = path.is_dir();
            if path.file_name()
                .and_then(|n| n.to_str())
                .map(|n| n.starts_with('.'))
                .unwrap_or(false)
            { continue; }

            if !is_dir {
                let ext = path.extension()
                    .and_then(|e| e.to_str())
                    .map(|e| format!(".{}", e.to_lowercase()));
                match ext {
                    Some(e) if ext_set.contains(&e) => {}
                    _ => continue,
                }
            }

            if let Some(fe) = build_file_entry(&path, is_dir) {
                out.push(fe);
            }
            if out.len() >= SCAN_MAX_ENTRIES { break; }
            if is_dir {
                walk_dir(&path, depth + 1, ext_set, visited, out);
                if out.len() >= SCAN_MAX_ENTRIES { break; }
            }
        }
        visited.remove(&canon);
    }

    fn build_file_entry(path: &Path, is_directory: bool) -> Option<FileEntry> {
        let name = path.file_name()?.to_str()?.to_string();
        let abs = path.canonicalize().unwrap_or_else(|_| path.to_path_buf());
        let abs_str = abs.to_string_lossy().into_owned();
        let (size, modified) = if is_directory {
            (None, None)
        } else {
            let meta = fs::metadata(path).ok();
            let size = meta.as_ref().map(|m| m.len());
            let modified = meta.and_then(|m| {
                m.modified().ok()
                    .and_then(|t| t.duration_since(UNIX_EPOCH).ok())
                    .map(|d| d.as_secs() as i64)
            });
            (size, modified)
        };
        Some(FileEntry {
            name, path: abs_str, is_directory, size, modified,
        })
    }

    fn sort_entries(entries: &mut [FileEntry]) {
        entries.sort_by(|a, b| {
            b.is_directory.cmp(&a.is_directory)
                .then_with(|| a.name.to_lowercase().cmp(&b.name.to_lowercase()))
        });
    }

    // -------------------------------------------------------------------
    // Library index (SQLite-backed)
    // -------------------------------------------------------------------
    use crate::library::{LibraryDb, LibraryIndex, Track};

    #[tauri::command]
    pub fn get_library_index(
        db: tauri::State<'_, Arc<LibraryDb>>,
    ) -> Result<LibraryIndex, String> {
        db.get_library_index()
    }

    #[tauri::command]
    pub fn rescan_library(
        db: tauri::State<'_, Arc<LibraryDb>>,
        path: String,
    ) -> Result<LibraryIndex, String> {
        db.rescan_library(&path)
    }

    #[tauri::command]
    pub fn search_library(
        db: tauri::State<'_, Arc<LibraryDb>>,
        query: String,
        limit: u32,
    ) -> Result<Vec<Track>, String> {
        db.search_library(&query, limit)
    }

    #[tauri::command]
    pub fn add_scan_root(
        db: tauri::State<'_, Arc<LibraryDb>>,
        path: String,
    ) -> Result<(), String> {
        db.add_scan_root(&path)
    }

    #[tauri::command]
    pub fn remove_scan_root(
        db: tauri::State<'_, Arc<LibraryDb>>,
        path: String,
    ) -> Result<(), String> {
        db.remove_scan_root(&path)
    }

    #[tauri::command]
    pub fn get_scan_roots(
        db: tauri::State<'_, Arc<LibraryDb>>,
    ) -> Result<Vec<String>, String> {
        db.get_scan_roots()
    }

    #[cfg(test)]
    mod tests {
        use super::*;
        use std::fs;
        use std::path::PathBuf;
        use std::sync::atomic::{AtomicU64, Ordering};

        static COUNTER: AtomicU64 = AtomicU64::new(0);

        fn unique_tmp_dir(label: &str) -> PathBuf {
            let n = COUNTER.fetch_add(1, Ordering::Relaxed);
            let pid = std::process::id();
            let dir = std::env::temp_dir()
                .join(format!("utoaudio-audio-ffi-test-{label}-{pid}-{n}"));
            fs::create_dir_all(&dir).expect("create tmp dir");
            dir
        }

        #[test]
        fn read_dir_entries_reports_is_directory_correctly() {
            let dir = unique_tmp_dir("read-dir-entries");
            let sub = dir.join("subdir");
            fs::create_dir(&sub).expect("create subdir");
            let file = dir.join("song.flac");
            fs::write(&file, b"hello").expect("write file");

            let entries = read_dir_entries(&dir).expect("read_dir_entries ok");
            assert_eq!(entries.len(), 2, "expected exactly two entries");

            let by_name: std::collections::HashMap<&str, &FileEntry> = entries
                .iter()
                .map(|e| (e.name.as_str(), e))
                .collect();

            let dir_entry = by_name
                .get("subdir")
                .expect("subdir entry present");
            assert!(
                dir_entry.is_directory,
                "subdir must have is_directory=true (was {})",
                dir_entry.is_directory
            );
            assert!(
                dir_entry.size.is_none(),
                "subdir must have size=None (was {:?})",
                dir_entry.size
            );

            let file_entry = by_name
                .get("song.flac")
                .expect("song.flac entry present");
            assert!(
                !file_entry.is_directory,
                "song.flac must have is_directory=false (was {})",
                file_entry.is_directory
            );
            assert_eq!(
                file_entry.size,
                Some(5),
                "song.flac must report its real size"
            );

            fs::remove_dir_all(&dir).ok();
        }
    }
} // end commands mod
