// This file is part of utoaudio, licensed under AGPL-3.0.
//
// `audio-ffi` - Tauri command bindings bridging the frontend to `audio-core`.

use std::sync::Arc;
use std::time::Duration;

use tokio::sync::Notify;

pub mod library;
pub mod lyrics;
pub mod playlist;
pub mod settings;

// Re-export the library DB handle so the Tauri shell can `use audio_ffi::LibraryDb`.
pub use library::LibraryDb;

// Re-export the lyric payload type so the Tauri shell can register the
// `load_lyrics` command with a typed return value.
pub use lyrics::LyricPayload;

// Re-export every serde-serializable type from `audio_core::tauri_api` so the
// frontend TypeScript bindings (generated by Tauri from the command
// signatures below) can reference them through this crate's namespace.
pub use audio_core::tauri_api::{
    AudioEngine, AudioEventInfo, ConvolverConfig, CrossfadeConfig,
    CrossfadeCurveSerde, EqualizerPreset, EQBand, FxConfig,
    PlaybackProgressInfo, PlaybackState, SongInfo, Uac2DeviceInfo,
};

pub use playlist::{PlaylistInfo, PlaylistTrackRow, M3u8ImportResult};

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FileEntry {
    pub name: String,
    pub path: String,
    pub is_directory: bool,
    pub size: Option<u64>,
    pub modified: Option<i64>,
    #[serde(default)]
    pub album_art_path: Option<String>,
    /// Tag-based track title (from ID3/Vorbis/FLAC tags). `None` for
    /// directories or untagged files — the frontend falls back to the
    /// filename in that case.
    #[serde(default)]
    pub title: Option<String>,
    /// Tag-based artist name.
    #[serde(default)]
    pub artist: Option<String>,
    /// Tag-based album name.
    #[serde(default)]
    pub album: Option<String>,
    /// Sample rate in Hz, read from the audio file's properties.
    #[serde(default)]
    pub sample_rate: Option<u32>,
    /// Bit depth in bits per sample (e.g. 16, 24). `None` for lossy formats.
    #[serde(default)]
    pub bits_per_sample: Option<u32>,
}

pub mod commands {
    use super::{
        Arc, AudioEngine, AudioEventInfo, ConvolverConfig, CrossfadeConfig,
        Duration, FileEntry, EqualizerPreset, FxConfig, Notify,
        PlaybackProgressInfo, PlaybackState, SongInfo, Uac2DeviceInfo,
    };
    use std::collections::HashSet;
    use std::fs;
    use std::path::{Path, PathBuf};
    use std::time::UNIX_EPOCH;
    use tauri::Emitter;
    use tauri::Manager;
    use std::sync::Mutex;
    use std::collections::HashMap;
    use lofty::prelude::*;
    use lofty::probe::Probe;
    use lofty::config::ParseOptions;
    use lofty::tag::ItemKey;
    use serde::{Deserialize, Serialize};

    static CURRENT_SONG_INFO: Mutex<Option<SongInfo>> = Mutex::new(None);
    static SONG_INFO_CACHE: Mutex<Option<HashMap<String, SongInfo>>> = Mutex::new(None);

    // -------------------------------------------------------------------
    // Lifecycle / capability commands
    // -------------------------------------------------------------------
    #[tauri::command]
    pub fn init(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<(), String> {
        engine.init();
        Ok(())
    }

    #[tauri::command]
    pub fn prepare(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        preferred_sample_rate: Option<u32>,
    ) -> Result<(), String> {
        engine
            .prepare(preferred_sample_rate)
            .map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn is_initialized(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<bool, String> {
        Ok(engine.is_initialized())
    }

    #[tauri::command]
    pub fn probe_audio_file(path: String) -> Result<audio_core::ProbeInfo, String> {
        audio_core::probe_audio_file(&path)
    }

    // -------------------------------------------------------------------
    // Playback commands
    // -------------------------------------------------------------------
    #[tauri::command]
    pub fn play(engine: tauri::State<'_, Arc<AudioEngine>>, song: SongInfo) -> Result<(), String> {
        eprintln!("[utoaudio] play: path={} sr={:?} bps={:?}", song.path, song.sample_rate, song.bits_per_sample);
        let preferred_sr = song.sample_rate;
        audio_core::set_preferred_bits_per_sample(song.bits_per_sample);
        if !engine.is_initialized() {
            engine.init();
            // Try the requested rate, then 48 kHz (common USB default),
            // then None. The first successful prepare "primes" the ALSA
            // device so subsequent re-prepares at other rates work.
            engine.prepare(preferred_sr)
                .or_else(|_| engine.prepare(Some(48_000)))
                .or_else(|_| engine.prepare(None))
                .map_err(|e| e.to_string())?;
        } else if preferred_sr.is_some() {
            engine.prepare(preferred_sr)
                .or_else(|_| engine.prepare(Some(48_000)))
                .or_else(|_| engine.prepare(None))
                .map_err(|e| e.to_string())?;
        }
        let play_result = engine.play(song.clone());
        eprintln!("[utoaudio] engine.play result: {:?}", play_result.is_ok());
        play_result.map_err(|e| e.to_string())?;

        // Cache the song info for NowPlaying retrieval and persist as last-played.
        if let Ok(mut cache) = SONG_INFO_CACHE.lock() {
            let map = cache.get_or_insert_with(HashMap::new);
            map.insert(song.path.clone(), song.clone());
        }
        if let Ok(mut cur) = CURRENT_SONG_INFO.lock() {
            *cur = Some(song.clone());
        }
        persist_last_played(&song);
        Ok(())
    }

    #[tauri::command]
    pub fn queue_next(engine: tauri::State<'_, Arc<AudioEngine>>, song: SongInfo) -> Result<(), String> {
        let preferred_sr = song.sample_rate;
        audio_core::set_preferred_bits_per_sample(song.bits_per_sample);
        if !engine.is_initialized() {
            engine.init();
            engine.prepare(preferred_sr)
                .or_else(|_| engine.prepare(Some(48_000)))
                .or_else(|_| engine.prepare(None))
                .map_err(|e| e.to_string())?;
        } else if preferred_sr.is_some() {
            engine.prepare(preferred_sr)
                .or_else(|_| engine.prepare(Some(48_000)))
                .or_else(|_| engine.prepare(None))
                .map_err(|e| e.to_string())?;
        }
        engine.queue_next(song.clone()).map_err(|e| e.to_string())?;

        if let Ok(mut cache) = SONG_INFO_CACHE.lock() {
            let map = cache.get_or_insert_with(HashMap::new);
            map.insert(song.path.clone(), song);
        }
        Ok(())
    }

    fn persist_last_played(song: &SongInfo) {
        use crate::settings::LastPlayedTrack;
        let track = LastPlayedTrack {
            path: song.path.clone(),
            title: song.title.clone(),
            artist: song.artist.clone(),
            album: song.album.clone(),
            duration_secs: song.duration_secs,
            album_art_path: song.album_art_path.clone(),
        };
        if let Ok(mut settings) = settings_load() {
            settings.last_played_track = Some(track);
            let _ = settings_save(&settings);
        }
    }

    #[tauri::command]
    pub fn get_current_song_info() -> Result<Option<SongInfo>, String> {
        Ok(CURRENT_SONG_INFO.lock().map_err(|e| e.to_string())?.clone())
    }

    #[tauri::command]
    pub fn set_current_song(path: String) -> Result<(), String> {
        let song = {
            let cache = SONG_INFO_CACHE.lock().map_err(|e| e.to_string())?;
            cache.as_ref().and_then(|m| m.get(&path)).cloned()
        };
        if let Some(ref s) = song {
            if let Ok(mut cur) = CURRENT_SONG_INFO.lock() {
                *cur = Some(s.clone());
            }
            persist_last_played(s);
        }
        Ok(())
    }

    #[tauri::command]
    pub fn pause(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<(), String> {
        engine.pause().map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn resume(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<(), String> {
        engine.resume().map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn stop(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<(), String> {
        engine.stop().map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn seek(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        position_secs: f64,
    ) -> Result<(), String> {
        engine.seek(position_secs).map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn set_volume(engine: tauri::State<'_, Arc<AudioEngine>>, volume: f32) -> Result<(), String> {
        engine.set_volume(volume).map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn get_state(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<PlaybackState, String> {
        Ok(engine.get_state())
    }

    #[tauri::command]
    pub fn get_progress(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<Option<PlaybackProgressInfo>, String> {
        Ok(engine.get_progress())
    }

    #[tauri::command]
    pub fn poll_event(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<Option<AudioEventInfo>, String> {
        Ok(engine.poll_event())
    }

    #[tauri::command]
    pub fn current_path(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<Option<String>, String> {
        Ok(engine.current_path())
    }

    #[tauri::command]
    pub fn skip_to_next(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<(), String> {
        engine.skip_to_next().map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn set_playback_speed(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        speed: f32,
    ) -> Result<(), String> {
        engine.set_playback_speed(speed).map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn playback_speed(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<Option<f32>, String> {
        Ok(engine.playback_speed())
    }

    #[tauri::command]
    pub fn sample_rate(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<Option<u32>, String> {
        Ok(engine.sample_rate())
    }

    #[tauri::command]
    pub fn channels(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<Option<usize>, String> {
        Ok(engine.channels())
    }

    // -------------------------------------------------------------------
    // DSP / FX commands
    // -------------------------------------------------------------------
    #[tauri::command]
    pub fn set_equalizer(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        preset: EqualizerPreset,
    ) -> Result<(), String> {
        engine.set_equalizer(&preset).map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn set_fx(engine: tauri::State<'_, Arc<AudioEngine>>, config: FxConfig) -> Result<(), String> {
        engine.set_fx(config).map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn set_convolver(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        config: ConvolverConfig,
    ) -> Result<(), String> {
        engine.set_convolver(config).map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn set_convolver_ir(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        coeffs: Vec<Vec<f32>>,
    ) -> Result<(), String> {
        engine.set_convolver_ir(coeffs).map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn clear_convolver_ir(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<(), String> {
        engine.clear_convolver_ir().map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn set_crossfade(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        config: CrossfadeConfig,
    ) -> Result<(), String> {
        engine.set_crossfade(config).map_err(|e| e.to_string())
    }

    // -------------------------------------------------------------------
    // High-res / bit-perfect preferences
    // -------------------------------------------------------------------
    #[tauri::command]
    pub fn set_high_res_mode(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        enabled: bool,
    ) -> Result<(), String> {
        engine.set_high_res_mode(enabled);
        Ok(())
    }

    #[tauri::command]
    pub fn set_dap_bit_perfect_enabled(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        enabled: bool,
    ) -> Result<(), String> {
        engine.set_dap_bit_perfect_enabled(enabled);
        Ok(())
    }

    #[tauri::command]
    pub fn set_432hz_tuning_enabled(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        enabled: bool,
    ) -> Result<(), String> {
        engine.set_432hz_tuning_enabled(enabled);
        Ok(())
    }

    // -------------------------------------------------------------------
    // Hardware queries / shutdown
    // -------------------------------------------------------------------
    #[tauri::command]
    pub fn is_dac_available(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        preferred_sample_rate: Option<u32>,
    ) -> Result<bool, String> {
        engine
            .is_dac_available(preferred_sample_rate)
            .map_err(|e| e.to_string())
    }

    #[cfg(target_os = "linux")]
    #[tauri::command]
    pub fn list_alsa_devices() -> Result<Vec<String>, String> {
        Ok(audio_core::list_alsa_output_devices())
    }

    #[cfg(target_os = "linux")]
    #[tauri::command]
    pub fn set_output_device(
        engine: tauri::State<'_, Arc<AudioEngine>>,
        backend: String,
        alsa_device: Option<String>,
    ) -> Result<(), String> {
        let mut current: AppSettings = settings_load().unwrap_or_default();
        current.output_device = Some(crate::settings::OutputDeviceSettings {
            backend: backend.clone(),
            alsa_device: alsa_device.clone(),
        });
        settings_save(&current)?;

        if backend == "alsa" {
            audio_core::set_linux_alsa_device(alsa_device);
        } else {
            // Switching back to PipeWire: release the ALSA device reservation
            // so PipeWire can reclaim the DAC, then clear the preference.
            #[cfg(target_os = "linux")]
            audio_core::release_reserved_alsa_device();
            audio_core::set_linux_alsa_device(None);
        }

        // Force engine rebuild on next prepare() so the new device takes effect.
        engine.shutdown().map_err(|e| e.to_string())?;
        engine.init();
        engine.prepare(None).map_err(|e| e.to_string())?;

        Ok(())
    }

    #[tauri::command]
    pub fn shutdown(engine: tauri::State<'_, Arc<AudioEngine>>) -> Result<(), String> {
        engine.shutdown().map_err(|e| e.to_string())
    }

    #[cfg(feature = "uac2")]
    #[tauri::command]
    pub fn list_uac2_devices(
        engine: tauri::State<'_, Arc<AudioEngine>>,
    ) -> Result<Vec<Uac2DeviceInfo>, String> {
        Ok(engine.list_uac2_devices())
    }

    #[tauri::command]
    pub fn version() -> Result<String, String> {
        Ok("utoaudio audio-ffi 0.1.0".to_string())
    }

    // -------------------------------------------------------------------
    // Event forwarding
    // -------------------------------------------------------------------
    #[tauri::command]
    pub async fn start_event_stream(
        app_handle: tauri::AppHandle,
        engine: tauri::State<'_, Arc<AudioEngine>>,
        shutdown: tauri::State<'_, Arc<Notify>>,
    ) -> Result<(), String> {
        let engine = Arc::clone(&engine);
        let shutdown = Arc::clone(&shutdown);
        tauri::async_runtime::spawn(async move {
            let mut ticker = tokio::time::interval(Duration::from_millis(100));
            ticker.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
            ticker.reset();
            loop {
                tokio::select! {
                    _ = shutdown.notified() => break,
                    _ = ticker.tick() => {
                        let mut drained = 0;
                        while let Some(event) = engine.poll_event() {
                            let _ = app_handle.emit("audio-event", event);
                            drained += 1;
                            if drained >= 256 {
                                break;
                            }
                        }
                        if let Some(progress) = engine.get_progress() {
                            let _ = app_handle.emit(
                                "audio-event",
                                AudioEventInfo::Progress { progress },
                            );
                        }
                    }
                }
            }
        });
        Ok(())
    }

    // -------------------------------------------------------------------
    // Persistent settings
    // -------------------------------------------------------------------
    use crate::settings::load_settings as settings_load;
    use crate::settings::save_settings as settings_save;
    use crate::settings::Settings as AppSettings;

    #[tauri::command]
    pub fn get_settings() -> Result<serde_json::Value, String> {
        let s = settings_load()?;
        Ok(serde_json::to_value(&s).map_err(|e| e.to_string())?)
    }

    #[tauri::command]
    pub fn set_settings(settings: serde_json::Value) -> Result<(), String> {
        let mut current: AppSettings = settings_load().unwrap_or_default();
        if let Ok(partial) = serde_json::from_value::<AppSettings>(settings) {
            if !partial.enabled_extensions.is_empty() {
                current.enabled_extensions = partial.enabled_extensions;
            }
            if partial.equalizer.is_some() {
                current.equalizer = partial.equalizer;
            }
            if partial.crossfade.is_some() {
                current.crossfade = partial.crossfade;
            }
            if partial.convolver.is_some() {
                current.convolver = partial.convolver;
            }
            if partial.lyric_font_size.is_some() {
                current.lyric_font_size = partial.lyric_font_size;
            }
            if partial.output_device.is_some() {
                current.output_device = partial.output_device;
            }
            if partial.last_played_track.is_some() {
                current.last_played_track = partial.last_played_track;
            }
            if partial.repeat_mode.is_some() {
                current.repeat_mode = partial.repeat_mode;
            }
            if partial.queue_index.is_some() {
                current.queue_index = partial.queue_index;
            }
        }
        settings_save(&current)?;
        Ok(())
    }

    // -------------------------------------------------------------------
    // Filesystem scan commands (Library page)
    // -------------------------------------------------------------------
    const SCAN_MAX_DEPTH: u32 = 8;
    const SCAN_MAX_ENTRIES: usize = 50_000;

    #[tauri::command]
    pub fn scan_directory(
        app_handle: tauri::AppHandle,
        path: String,
    ) -> Result<Vec<FileEntry>, String> {
        let root = PathBuf::from(&path);
        if !root.is_dir() {
            return Err(format!("not a directory: {}", path));
        }
        let art_dir = ensure_art_cache_dir(&app_handle);
        read_dir_entries(&root, &art_dir).map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub async fn scan_library(
        app_handle: tauri::AppHandle,
        roots: Vec<String>,
        extensions: Vec<String>,
    ) -> Result<Vec<FileEntry>, String> {
        let art_dir = ensure_art_cache_dir(&app_handle);
        let handle = app_handle.clone();
        tauri::async_runtime::spawn_blocking(move || {
            scan_library_inner(roots, extensions, &art_dir, Some(&handle))
        })
        .await
        .map_err(|e| e.to_string())?
    }

    /// Shared scanning logic used by both the `scan_library` command and
    /// `LibraryDb::rescan_library`. Takes an explicit art cache directory
    /// instead of resolving it from an `AppHandle`.
    ///
    /// When `app_handle` is `Some`, progress events are emitted as
    /// `"scan-progress"` Tauri events during the walk so the frontend can
    /// show a live progress indicator.
    pub(crate) fn scan_library_inner(
        roots: Vec<String>,
        extensions: Vec<String>,
        art_dir: &PathBuf,
        app_handle: Option<&tauri::AppHandle>,
    ) -> Result<Vec<FileEntry>, String> {
        let ext_set: HashSet<String> = extensions
            .into_iter()
            .map(|e| {
                let t = e.trim().to_lowercase();
                if t.starts_with('.') { t } else { format!(".{}", t) }
            })
            .collect();

        let mut entries = Vec::new();
        let mut visited = HashSet::new();

        for root_str in &roots {
            let root = PathBuf::from(root_str);
            let canon = root.canonicalize().unwrap_or_else(|_| root.clone());
            if !canon.is_dir() { continue; }
            let base_offset = entries.len();
            walk_dir(&canon, 0, &ext_set, &mut visited, &mut entries, base_offset, art_dir, app_handle);
            if entries.len() >= SCAN_MAX_ENTRIES { break; }
        }

        sort_entries(&mut entries);
        let total = entries.len().min(SCAN_MAX_ENTRIES);
        entries.truncate(SCAN_MAX_ENTRIES);

        if let Some(handle) = app_handle {
            let _ = handle.emit("scan-progress", serde_json::json!({
                "phase": "complete",
                "current": total,
                "total": total,
            }));
        }

        Ok(entries)
    }

    fn ensure_art_cache_dir(app_handle: &tauri::AppHandle) -> PathBuf {
        let data_dir = app_handle.path().app_data_dir().unwrap_or_else(|_| PathBuf::from("/tmp"));
        let art_dir = data_dir.join("utoaudio").join("art");
        let _ = std::fs::create_dir_all(&art_dir);
        art_dir
    }

    fn read_dir_entries(dir: &Path, art_dir: &PathBuf) -> std::io::Result<Vec<FileEntry>> {
        let mut out = Vec::new();
        for entry in fs::read_dir(dir)? {
            let entry = match entry { Ok(e) => e, Err(_) => continue };
            let is_dir = entry.file_type().map(|ft| ft.is_dir()).unwrap_or(false);
            if let Some(fe) = build_file_entry(&entry.path(), is_dir, art_dir) {
                out.push(fe);
            }
        }
        sort_entries(&mut out);
        Ok(out)
    }

    fn walk_dir(
        dir: &Path, depth: u32,
        ext_set: &HashSet<String>,
        visited: &mut HashSet<PathBuf>,
        out: &mut Vec<FileEntry>,
        base_offset: usize,
        art_dir: &PathBuf,
        app_handle: Option<&tauri::AppHandle>,
    ) {
        if depth >= SCAN_MAX_DEPTH { return; }
        let canon = dir.canonicalize().unwrap_or_else(|_| dir.to_path_buf());
        if !visited.insert(canon.clone()) { return; }

        let iter = match fs::read_dir(dir) {
            Ok(it) => it,
            Err(_) => { visited.remove(&canon); return; }
        };

        for entry in iter.flatten() {
            let path = entry.path();
            let is_dir = path.is_dir();
            if path.file_name()
                .and_then(|n| n.to_str())
                .map(|n| n.starts_with('.'))
                .unwrap_or(false)
            { continue; }

            if !is_dir {
                let ext = path.extension()
                    .and_then(|e| e.to_str())
                    .map(|e| format!(".{}", e.to_lowercase()));
                match ext {
                    Some(e) if ext_set.contains(&e) => {}
                    _ => continue,
                }
            }

            if let Some(fe) = build_file_entry(&path, is_dir, art_dir) {
                out.push(fe);
            }
            if let Some(handle) = app_handle {
                if out.len() % 100 == 0 {
                    let root_label = dir.to_string_lossy().into_owned();
                    let _ = handle.emit("scan-progress", serde_json::json!({
                        "phase": "scanning",
                        "current": out.len() + base_offset,
                        "root": root_label,
                    }));
                }
            }
            if out.len() >= SCAN_MAX_ENTRIES { break; }
            if is_dir {
                walk_dir(&path, depth + 1, ext_set, visited, out, base_offset, art_dir, app_handle);
                if out.len() >= SCAN_MAX_ENTRIES { break; }
            }
        }
        visited.remove(&canon);
    }

    fn build_file_entry(path: &Path, is_directory: bool, art_dir: &PathBuf) -> Option<FileEntry> {
        let name = path.file_name()?.to_str()?.to_string();
        let abs = path.canonicalize().unwrap_or_else(|_| path.to_path_buf());
        let abs_str = abs.to_string_lossy().into_owned();
        let (size, modified) = if is_directory {
            (None, None)
        } else {
            let meta = fs::metadata(path).ok();
            let size = meta.as_ref().map(|m| m.len());
            let modified = meta.and_then(|m| {
                m.modified().ok()
                    .and_then(|t| t.duration_since(UNIX_EPOCH).ok())
                    .map(|d| d.as_secs() as i64)
            });
            (size, modified)
        };
        let (album_art_path, title, artist, album, sample_rate, bits_per_sample) = if is_directory {
            (None, None, None, None, None, None)
        } else {
            let art = crate::library::discover_album_art(&abs_str, art_dir);
            let (title, artist, album, sr, bps) = read_audio_meta(&abs_str);
            (art, title, artist, album, sr, bps)
        };
        Some(FileEntry {
            name,
            path: abs_str,
            is_directory,
            size,
            modified,
            album_art_path,
            title,
            artist,
            album,
            sample_rate,
            bits_per_sample,
        })
    }

    /// Read the track title, artist, album, sample rate, and bit depth from
    /// an audio file's tags + properties in a single lofty pass.
    fn read_audio_meta(path: &str) -> (Option<String>, Option<String>, Option<String>, Option<u32>, Option<u32>) {
        let parse_options = ParseOptions::new().read_properties(true);
        let probe = match Probe::open(path) {
            Ok(p) => p.options(parse_options),
            Err(_) => return (None, None, None, None, None),
        };
        let probe = match probe.guess_file_type() {
            Ok(p) => p,
            Err(_) => return (None, None, None, None, None),
        };
        let tagged_file = match probe.read() {
            Ok(f) => f,
            Err(_) => return (None, None, None, None, None),
        };
        let tag = tagged_file.primary_tag().or_else(|| tagged_file.first_tag());
        let title = tag.and_then(|t| t.get_string(&ItemKey::TrackTitle).map(|s| s.to_string()));
        let artist = tag.and_then(|t| t.get_string(&ItemKey::TrackArtist).map(|s| s.to_string()));
        let album = tag.and_then(|t| t.get_string(&ItemKey::AlbumTitle).map(|s| s.to_string()));
        let props = tagged_file.properties();
        let sample_rate = props.sample_rate();
        let bits_per_sample = props.bit_depth().map(|b| b as u32);
        (title, artist, album, sample_rate, bits_per_sample)
    }

    fn sort_entries(entries: &mut [FileEntry]) {
        entries.sort_by(|a, b| {
            b.is_directory.cmp(&a.is_directory)
                .then_with(|| a.name.to_lowercase().cmp(&b.name.to_lowercase()))
        });
    }

    #[tauri::command]
    pub fn get_album_art_data(path: String) -> Result<Vec<u8>, String> {
        std::fs::read(&path).map_err(|e| e.to_string())
    }

    /// Re-discover album art for a given audio file path. Returns the cached
    /// art file path (extracting from tags on first call). Used by the Now
    /// Playing page to recover album art when the persisted `album_art_path`
    /// is missing (e.g. older settings saved before art extraction was wired).
    #[tauri::command]
    pub fn get_album_art_path(
        app_handle: tauri::AppHandle,
        audio_path: String,
    ) -> Result<Option<String>, String> {
        let art_dir = ensure_art_cache_dir(&app_handle);
        Ok(crate::library::discover_album_art(&audio_path, &art_dir))
    }

    #[tauri::command]
    pub fn read_text_file(path: String) -> Result<String, String> {
        std::fs::read_to_string(&path).map_err(|e| e.to_string())
    }

    #[tauri::command]
    pub fn file_exists(path: String) -> Result<bool, String> {
        Ok(PathBuf::from(&path).is_file())
    }

    #[tauri::command]
    pub fn get_embedded_lyrics(path: String) -> Result<Option<String>, String> {
        let parse_options = ParseOptions::new().read_properties(false);
        let tagged_file = Probe::open(&path)
            .map_err(|e| e.to_string())?
            .options(parse_options)
            .guess_file_type()
            .map_err(|e| e.to_string())?
            .read()
            .map_err(|e| e.to_string())?;
        let tag = match tagged_file.primary_tag().or_else(|| tagged_file.first_tag()) {
            Some(t) => t,
            None => return Ok(None),
        };
        Ok(tag.get_string(&ItemKey::Lyrics).map(|s| s.to_string()))
    }

    #[tauri::command]
    pub fn load_lyrics(path: String) -> Result<Option<crate::LyricPayload>, String> {
        crate::lyrics::load_lyrics(&path)
    }

    #[derive(Debug, Clone, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct SongMetadata {
        pub title: Option<String>,
        pub artist: Option<String>,
        pub album: Option<String>,
    }

    #[tauri::command]
    pub fn get_song_metadata(path: String) -> Result<SongMetadata, String> {
        let parse_options = ParseOptions::new().read_properties(false);
        let tagged_file = Probe::open(&path)
            .map_err(|e| e.to_string())?
            .options(parse_options)
            .guess_file_type()
            .map_err(|e| e.to_string())?
            .read()
            .map_err(|e| e.to_string())?;
        let tag = tagged_file.primary_tag().or_else(|| tagged_file.first_tag());
        Ok(SongMetadata {
            title: tag.and_then(|t| t.get_string(&ItemKey::TrackTitle).map(|s| s.to_string())),
            artist: tag.and_then(|t| t.get_string(&ItemKey::TrackArtist).map(|s| s.to_string())),
            album: tag.and_then(|t| t.get_string(&ItemKey::AlbumTitle).map(|s| s.to_string())),
        })
    }

    // -------------------------------------------------------------------
    // Library index (SQLite-backed)
    // -------------------------------------------------------------------
    use crate::library::{LibraryDb, LibraryIndex, QueueTrack, Track};

    #[tauri::command]
    pub fn get_library_index(
        db: tauri::State<'_, Arc<LibraryDb>>,
    ) -> Result<LibraryIndex, String> {
        db.get_library_index()
    }

    #[tauri::command]
    pub async fn rescan_library(
        db: tauri::State<'_, Arc<LibraryDb>>,
        path: String,
        app_handle: tauri::AppHandle,
    ) -> Result<LibraryIndex, String> {
        let db = db.inner().clone();
        let handle = app_handle.clone();
        tauri::async_runtime::spawn_blocking(move || {
            db.rescan_library(&path, Some(&handle))
        })
        .await
        .map_err(|e| e.to_string())?
    }

    #[tauri::command]
    pub fn search_library(
        db: tauri::State<'_, Arc<LibraryDb>>,
        query: String,
        limit: u32,
    ) -> Result<Vec<Track>, String> {
        db.search_library(&query, limit)
    }

    #[tauri::command]
    pub fn add_scan_root(
        db: tauri::State<'_, Arc<LibraryDb>>,
        path: String,
    ) -> Result<(), String> {
        db.add_scan_root(&path)
    }

    #[tauri::command]
    pub fn remove_scan_root(
        db: tauri::State<'_, Arc<LibraryDb>>,
        path: String,
    ) -> Result<(), String> {
        db.remove_scan_root(&path)
    }

    #[tauri::command]
    pub fn get_scan_roots(
        db: tauri::State<'_, Arc<LibraryDb>>,
    ) -> Result<Vec<String>, String> {
        db.get_scan_roots()
    }

    // -------------------------------------------------------------------
    // Playback queue (SQLite-backed)
    // -------------------------------------------------------------------

    #[tauri::command]
    pub fn set_playback_queue(
        db: tauri::State<'_, Arc<LibraryDb>>,
        tracks: Vec<QueueTrack>,
    ) -> Result<(), String> {
        db.set_queue(&tracks)
    }

    #[tauri::command]
    pub fn get_playback_queue(
        db: tauri::State<'_, Arc<LibraryDb>>,
    ) -> Result<Vec<QueueTrack>, String> {
        db.get_queue()
    }

    #[tauri::command]
    pub fn clear_playback_queue(
        db: tauri::State<'_, Arc<LibraryDb>>,
    ) -> Result<(), String> {
        db.clear_queue()
    }

    #[cfg(test)]
    mod tests {
        use super::*;
        use std::fs;
        use std::path::PathBuf;
        use std::sync::atomic::{AtomicU64, Ordering};

        static COUNTER: AtomicU64 = AtomicU64::new(0);

        fn unique_tmp_dir(label: &str) -> PathBuf {
            let n = COUNTER.fetch_add(1, Ordering::Relaxed);
            let pid = std::process::id();
            let dir = std::env::temp_dir()
                .join(format!("utoaudio-audio-ffi-test-{label}-{pid}-{n}"));
            fs::create_dir_all(&dir).expect("create tmp dir");
            dir
        }

        #[test]
        fn read_dir_entries_reports_is_directory_correctly() {
            let dir = unique_tmp_dir("read-dir-entries");
            let sub = dir.join("subdir");
            fs::create_dir(&sub).expect("create subdir");
            let file = dir.join("song.flac");
            fs::write(&file, b"hello").expect("write file");

            let art_dir = std::env::temp_dir().join("utoaudio-test-art");
            let _ = std::fs::create_dir_all(&art_dir);
            let entries = read_dir_entries(&dir, &art_dir).expect("read_dir_entries ok");
            assert_eq!(entries.len(), 2, "expected exactly two entries");

            let by_name: std::collections::HashMap<&str, &FileEntry> = entries
                .iter()
                .map(|e| (e.name.as_str(), e))
                .collect();

            let dir_entry = by_name
                .get("subdir")
                .expect("subdir entry present");
            assert!(
                dir_entry.is_directory,
                "subdir must have is_directory=true (was {})",
                dir_entry.is_directory
            );
            assert!(
                dir_entry.size.is_none(),
                "subdir must have size=None (was {:?})",
                dir_entry.size
            );

            let file_entry = by_name
                .get("song.flac")
                .expect("song.flac entry present");
            assert!(
                !file_entry.is_directory,
                "song.flac must have is_directory=false (was {})",
                file_entry.is_directory
            );
            assert_eq!(
                file_entry.size,
                Some(5),
                "song.flac must report its real size"
            );

            fs::remove_dir_all(&dir).ok();
        }
    }
} // end commands mod
